# Generated by Django 3.2 on 2021-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='information',
        ),
        migrations.AddField(
            model_name='about',
            name='desc1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='desc2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='desc3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='gif',
            field=models.ImageField(null=True, upload_to='img/services'),
        ),
    ]
