# Generated by Django 3.2 on 2021-06-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20210622_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
